server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/statistics_db
    username: user
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update